name: fastq_screen_screen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl=5.26.2
  - bowtie2=2.4.5
  - bowtie=1.3.1
  - bwa=0.7.17
  - minimap2=2.24
  - samtools=1.16.1
  - bismark=0.24.0
  - perl-gd=2.73
  - perl-gdgraph=1.56