process MAKE_HTML_REPORT {
    tag "$meta.id"
    label 'process_single'

    // HTML report generation is handled natively by fastq-screen
    // This process ensures the HTML files are properly published

    input:
    tuple val(meta), path(results)
    tuple val(meta), path(png), optional: true

    output:
    tuple val(meta), path("*.html"), emit: html
    path "versions.yml", emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: "${meta.id}"
    
    """
    # FastQ Screen generates HTML reports automatically
    # This process just ensures they are captured and published
    echo "HTML report generation is handled by fastq-screen itself" > html_status.txt
    
    # Check if HTML files were generated by the main process
    if ls *_screen.html 1> /dev/null 2>&1; then
        echo "HTML report found and will be published"
    else
        # If no HTML was generated, create a simple one
        cat > ${prefix}_screen.html << EOF
<!DOCTYPE html>
<html>
<head>
    <title>FastQ Screen Report - ${meta.id}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { background-color: #4CAF50; color: white; padding: 20px; }
        pre { background-color: #f4f4f4; padding: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>FastQ Screen Report</h1>
    </div>
    <h2>Results for: ${meta.id}</h2>
    <pre>
EOF
        # Include the text results in the HTML
        if [ -f "${results}" ]; then
            cat "${results}" >> ${prefix}_screen.html
        fi
        echo "</pre></body></html>" >> ${prefix}_screen.html
    fi

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        fastq_screen: \$(echo "HTML reporting integrated")
    END_VERSIONS
    """

    stub:
    def prefix = task.ext.prefix ?: "${meta.id}"
    """
    echo '<!DOCTYPE html><html><head><title>FastQ Screen Report</title></head><body><h1>FastQ Screen Report</h1><p>Report for ${prefix}</p></body></html>' > ${prefix}_screen.html
    
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        fastq_screen: \$(echo "HTML reporting integrated")
    END_VERSIONS
    """
}