process MAKE_GRAPHS {
    tag "$meta.id"
    label 'process_single'

    // Graph generation is handled natively by fastq-screen
    // This process ensures the PNG files are properly published

    input:
    tuple val(meta), path(results)
    val bisulfite

    output:
    tuple val(meta), path("*.png"), emit: png, optional: true
    path "versions.yml", emit: versions

    when:
    task.ext.when == null || task.ext.when

    script:
    def args = task.ext.args ?: ''
    def prefix = task.ext.prefix ?: "${meta.id}"
    
    """
    # FastQ Screen generates PNG graphs automatically if GD::Graph is available
    # This process just ensures they are captured and published
    echo "Graph generation is handled by fastq-screen itself" > graph_status.txt
    
    # Check if PNG files were generated by the main process
    if ls *_screen.png 1> /dev/null 2>&1; then
        echo "PNG graphs found and will be published"
    else
        echo "No PNG graphs found - GD::Graph may not be available"
    fi

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        fastq_screen: \$(echo "Graph handling integrated")
    END_VERSIONS
    """

    stub:
    def prefix = task.ext.prefix ?: "${meta.id}"
    """
    touch ${prefix}_screen.png
    
    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        fastq_screen: \$(echo "Graph handling integrated")
    END_VERSIONS
    """
}